### ISSUE TITLE
Bug: Failed Deploy

### ISSUE THREAD

**Issue by CCallahanIV** [PuPy-Python/mentorship-app#84]
> Traceback (most recent call last):
>         File "manage.py", line 22, in <module>
>           execute_from_command_line(sys.argv)
>         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
>           utility.execute()
>         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
           self.fetch_command(subcommand).run_from_argv(self.argv)
>         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
           self.execute(*args, **cmd_options)
>         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
           output = self.handle(*args, **options)
>         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
           collected = self.collect()
>         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 115, in collect
           for path, storage in finder.list(self.ignore_patterns):
>         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/finders.py", line 112, in list
           for path in utils.get_files(storage, ignore_patterns):
>         File "/app/.heroku/python/lib/python3.6/site-packages/django/contrib/staticfiles/utils.py", line 28, in get_files
           directories, files = storage.listdir(location)
>         File "/app/.heroku/python/lib/python3.6/site-packages/django/core/files/storage.py", line 397, in listdir
           for entry in os.listdir(path):
>       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/build_adc5060b8459f19bbec11b07b9532566/build/static'
> !     Error while running '$ python manage.py collectstatic --noinput'.
>       See traceback above for details.
>       You may need to update application code to resolve this error.
>       Or, you can disable collectstatic for this application:
>          $ heroku config:set DISABLE_COLLECTSTATIC=1
>       https://devcenter.heroku.com/articles/django-assets
> !     Push rejected, failed to compile Python app.
> !     Push failed

**Comment by justinhernandez** [comment]
Could not reproduce the deployment bug.

App deployed successfully: https://damp-caverns-78996.herokuapp.com/

<img width="766" alt="screen shot 2018-09-11 at 7 47 09 pm" src="https://user-images.githubusercontent.com/23852/45399115-bf8e6880-b5fb-11e8-9a19-6afdd67211a4.png">

<img width="999" alt="screen shot 2018-09-11 at 7 47 42 pm" src="https://user-images.githubusercontent.com/23852/45399118-c1f0c280-b5fb-11e8-8c06-2fb03ccd6796.png">

**Comment by justinhernandez** [comment]
I can see that the PuPy build is still failing but for my own personal one it is not.

Maybe the diff between my branch and PuPy/master will shed some lilght.

![screencapture-travis-ci-org-justinhernandez-mentorship-app-jobs-432285235-2018-09-23-17_53_32](https://user-images.githubusercontent.com/23852/45934913-a53c7f00-bf59-11e8-805f-b8fb1ddac6aa.jpg)
